version: '3'
services: 
  mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123asd
    volumes:
      - ~/media/b2/file_storage/volumes-docker/mongodb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongoExpress    
    restart: always
    ports:
      - 8099:8081
    networks:
      - mongo-compose-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123asd      
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 123asd
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev      
    depends_on:
      - mongo


networks: 
    mongo-compose-network:
      driver: bridge